---
title: "ex_05"
author: "Nikolai German"
date: "`r Sys.Date()`"
output: html_document
execute: 
  warning: false
  message: false
  echo: false
---


```{r}
getMaxProfit <- function(price.changes) {
  checkmate::assertNumeric(price.changes, lower = 0,
  any.missing = FALSE, finite = TRUE, min.len = 1)
  n <- length(price.changes)
  max.profit <- 1.0
  for (day.buy in seq_len(n)) {
    # loop to n + 1 to sell after the last day
    for (day.sell in seq(day.buy + 1, n + 1)) {
      profit <- prod(price.changes[seq(day.buy, day.sell - 1)])
      if (profit > max.profit) {
      max.profit <- profit
      }
    }
  }
max.profit
}

getMaxProfit(c(1.1, .99, 1.2, 1.2, .5))
```

```{r}
getMaxProfit2 <- function(price.changes) {
  checkmate::assertNumeric(price.changes, lower = 0,
  any.missing = FALSE, finite = TRUE, min.len = 1)
  n <- length(price.changes)
  max.profit <- 1.0
  for (day.buy in seq_len(n)) {
    # loop to n + 1 to sell after the last day
    profit <- 1.0
    for (day.sell in seq(day.buy + 1, n + 1)) {
      profit <- profit * price.changes[[day.sell - 1]]
      # profit <- prod(price.changes[seq(day.buy, day.sell - 1)])
      if (profit > max.profit) {
      max.profit <- profit
      }
    }
  }
max.profit
}

getMaxProfit2(c(1.1, .99, 1.2, 1.2, .5))
```


```{r}
getMaxProfit3 <- function(price.changes) {
  checkmate::assertNumeric(price.changes, lower = 0,
  any.missing = FALSE, finite = TRUE, min.len = 1)
  
  log.price.changes <- log(price.changes)
  
  current.profit <- 0
  max.profit <- 0
  
  for (i in seq_along(log.price.changes)) {
    current.profit <- max(0, current.profit + log.price.changes[[i]])
    if (current.profit > max.profit) {
      max.profit <- current.profit
    }
  }
  exp(max.profit)
}

getMaxProfit3(c(1.1, .7, 1.2, 1.2, .5))

```

Ex. 3 'atime'

```{r warning=FALSE}
f1 <- function(N) sample(seq_len(N))
f2 <- function(N) seq_len(N)
f3 <- function(N, times = 10) {
  prop <- seq_len(times*N)
  logi.prop <- sample(rep(c(1, rep(0, 9)), times))
  prop[as.logical(logi.prop)]
}

funs <- list(f1, f2, f3)
result <- list()

for (i in seq_along(funs)) {
  result[[i]] <- atime::atime(
    setup = {
      x = funs[[i]](N)
    },
    radix = sort(x, method = "radix"),
    shell = sort(x, method = "shell"),
    quick = sort(x, method = "quick")
  )
}

plot(result[[1]])
plot(result[[2]])
plot(result[[3]])
```

```{r warning=FALSE}
result <- atime::atime(
    setup = {
      x = runif(N)
    },
    mean = mean(x),
    length = length(x),
    unique = unique(x),
    any = any(x > 0),
    all = all(x > 0),
    sort = sort(x),
    del.first = x[-1],
    del.last = x[-length(x)]
  )

plot(result)

```


